workflows:
  android-app:
    name: Bilimiao2 Android App
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.a985.bilimiao2"
      java: 11
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Update packages
        script: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      
      - name: Set up Protobuf
        script: |
          PROTOC_ZIP=protoc-3.12.0-linux-x86_64.zip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.12.0/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
          protoc --version
      
      - name: Set execution permission for Gradle
        script: |
          chmod +x gradlew
      
      - name: Build Android app
        script: |
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace --info
    
    artifacts:
      - app/build/outputs/**/*.apk
