workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      vars:
        PROJECT_DIR: "." # Project root
        ANDROID_BUILD_DIR: "$PROJECT_DIR/app/build"
    scripts:
      - name: Build with Gradle
        script: |
          cd $PROJECT_DIR
          ./gradlew clean assembleRelease
    artifacts:
      - $ANDROID_BUILD_DIR/outputs/**/*.apk
