workflows:
  android-app:
    name: Bilimiao2 Android App
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.a985.bilimiao2"  # 为bilimiao2项目设置的包名
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Set execution permission to Gradle
        script: |
          chmod +x gradlew
      - name: Build Android app
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
